import { chromium } from "/home/leif/lets-get-rich/claude_ops/.claude/skills/tcw-quote/node_modules/playwright/index.mjs";
import { readFileSync } from "node:fs";
const S = process.env.SHOTS, BASE = process.env.BASE ?? "http://127.0.0.1:8789";
const fixture = readFileSync("/home/leif/lets-get-rich/woodshed/tests/fixtures/logbook-v1.json", "utf8");
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 420, height: 860 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(`pageerror: ${e.message}`));
page.on("console", (m) => { if (m.type() === "error") errors.push(`console: ${m.text()}`); });
page.on("dialog", (d) => d.accept());
const shot = (n) => page.screenshot({ path: `${S}/${n}.png` });
const lb = (fn, ...args) => page.evaluate(async ([src, a]) => { const m = await import("/js/lib/logbook.js"); return (new Function("m", "a", src))(m, a); }, [`return (${fn})(m, a)`, args]);
const step = async (name, f) => { try { await f(); console.log("ok  ", name); } catch (e) { console.log("FAIL", name, "—", e.message); await shot(`fail-${name.replace(/\W+/g, "_")}`); throw e; } };
const gone = (pg = page) => pg.waitForFunction(() => !document.querySelector(".lb-ceremony"), null, { timeout: 6000 });
const text = async (sel) => (await page.locator(sel).first().textContent())?.trim();

await step("fresh Today empty state", async () => {
  await page.goto(`${BASE}/?app=1#/logbook`);
  await page.waitForSelector(".lb-hero.idle");
  if (!(await text(".lb-hero-total")).includes("press play")) throw new Error("empty copy missing");
  await shot("01-today-empty");
});
await step("play → picker → search-to-create Scales (technique)", async () => {
  await page.click("#lb-play");
  await page.waitForSelector(".lb-picker-wrap.open");
  await shot("02-picker-empty");
  await page.fill("#lb-pick-q", "Scales");
  await page.keyboard.press("Enter");
  await page.waitForSelector(".lb-create-wrap.open #lb-create-name");
  await page.waitForFunction(() => document.activeElement?.id === "lb-create-name");
  if ((await page.inputValue("#lb-create-name")) !== "Scales") throw new Error("name not prefilled");
  await page.click('.lb-typechip[data-type="technique"]');
  await shot("03-create-sheet");
  await page.keyboard.press("Enter");
  await page.waitForSelector(".lb-ceremony.engage.in");
  if ((await text(".lb-cer-goal")) !== "Scales") throw new Error("engage goal");
  await page.waitForTimeout(350);
  await shot("03b-engage");
  // the curtain swallows input: a tap on the hero underneath must not reach it
  const blocked = await page.evaluate(() => document.elementFromPoint(innerWidth / 2, innerHeight / 2)?.closest(".lb-ceremony") !== null);
  if (!blocked) throw new Error("engage does not block");
  await gone();
  await page.waitForSelector(".lb-hero.running");
  await page.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  if ((await text("#lb-hero-goal")) !== "Scales") throw new Error("hero goal " + await text("#lb-hero-goal"));
  if (!(await text(".lb-hero-type")).includes("technique")) throw new Error("type badge");
  await page.waitForSelector('.lb-trow[data-id]');
  await shot("04-running-scales");
});
await step("shell chip shows goal", async () => {
  await page.waitForSelector(".session-chip:not([hidden])");
  if ((await text(".session-goal")) !== "Scales") throw new Error("chip goal");
});
await step("switch → new piece Pathétique (segment backdated 30 min)", async () => {
  await lb((m) => { const s = m.logbook.running().segment; s.startedAt -= 30 * 60000; m.logbook.save(); });
  await page.waitForFunction(() => document.querySelector("#lb-elapsed")?.textContent.startsWith("30:"));
  await page.click("#lb-switch");
  await page.waitForSelector(".lb-picker-wrap.open");
  const now = await text(".lb-pick-row .lb-pick-sub");
  await page.fill("#lb-pick-q", "Pathétique Sonata — 1st mvt");
  await page.keyboard.press("Enter");
  await page.waitForSelector(".lb-create-wrap.open");
  await page.waitForFunction(() => document.activeElement?.id === "lb-create-name");
  await page.keyboard.press("Enter");
  await page.waitForFunction(() => document.querySelector("#lb-hero-goal")?.textContent.startsWith("Pathétique"));
  await page.waitForFunction(() => document.querySelectorAll(".lb-trow").length === 2);
  const w = await page.evaluate(() => ({ vw: innerWidth, doc: document.documentElement.scrollWidth }));
  if (w.vw > 420 || w.doc > 420) throw new Error("page widened (header overflow) " + JSON.stringify(w));
  const rows = await page.locator(".lb-trow-name").allTextContents();
  if (!rows.includes("Scales")) throw new Error("rows " + rows);
  const scalesMin = await page.locator('.lb-trow[data-id]:not(.live) .lb-trow-min').first().textContent();
  if (scalesMin.trim() !== "30m") throw new Error("scales minutes " + scalesMin);
  await shot("05-running-pathetique");
});
await step("+ note from the hero → last note shows", async () => {
  await page.click("#lb-hero-addnote");
  await page.waitForSelector(".lb-note-wrap.open textarea");
  await page.fill(".lb-note-wrap textarea", "Work mm. 93–108 slowly.\nLH jumps were the weak point.");
  await page.click("#lb-note-save");
  await page.waitForFunction(() => document.querySelector(".lb-hero-note-body")?.textContent.includes("93–108"));
  if (!(await text(".lb-hero-note-head")).includes("last note · today")) throw new Error("note head");
  await shot("06-hero-with-note");
});
await step("stop → idle, total, both rows", async () => {
  await lb((m) => { const s = m.logbook.running().segment; s.startedAt -= 62 * 60000; m.logbook.save(); });
  await page.click("#lb-stop");
  await page.waitForSelector(".lb-ceremony.bow.in");
  await page.waitForFunction(() => document.querySelector(".lb-cer-num")?.textContent.trim() === "1h 02m", null, { timeout: 3000 });
  if (!(await text(".lb-cer-on")).includes("Pathétique")) throw new Error("bow goal");
  if (!(await text(".lb-cer-sub")).includes("today on this goal")) throw new Error("bow sub");
  await page.waitForTimeout(250);
  await shot("07a-bow");
  await page.waitForTimeout(400);
  await page.mouse.click(210, 430); // tap-through after the minimum hold
  await gone();
  await page.waitForSelector(".lb-hero.idle");
  const total = await text(".lb-hero-total");
  if (!total.includes("1h 32m")) throw new Error("total " + total);
  await shot("07-stopped");
  if (!(await page.locator(".session-chip").isHidden())) throw new Error("chip visible");
});
await step("goals tab: library, search, sort", async () => {
  await page.click('.lb-strip [data-go="/goals"]');
  await page.waitForSelector(".lb-library");
  if ((await page.locator("#lb-active .lb-row").count()) !== 2) throw new Error("rows");
  await page.selectOption("#lb-lib-sort", "time");
  const first = await text("#lb-active .lb-row-title");
  if (!first.startsWith("Pathétique")) throw new Error("sort time → " + first);
  await page.fill("#lb-lib-q", "sca");
  await page.waitForFunction(() => document.querySelectorAll("#lb-active .lb-row").length === 1);
  await page.fill("#lb-lib-q", "");
  await page.click('.lb-filterchips [data-type="technique"]');
  await page.waitForFunction(() => document.querySelectorAll("#lb-active .lb-row").length === 1);
  await page.click('.lb-filterchips [data-type=""]');
  await shot("08-library");
});
await step("+ goal from library (Other · Sight reading) → stamp", async () => {
  await page.click("#lb-lib-add");
  await page.waitForSelector(".lb-create-wrap.open");
  await page.click('.lb-typechip[data-type="other"]');
  await page.fill("#lb-create-name", "Sight reading");
  await page.keyboard.press("Enter");
  await page.waitForFunction(() => document.querySelectorAll("#lb-active .lb-row").length === 3);
});
await step("goal page: rename, retype, note, practice list, practice this", async () => {
  await page.click('.lb-row-main[data-open]:has-text("Scales")');
  await page.waitForSelector(".lb-goalpage");
  const bb = await page.evaluate(() => { const p = document.querySelector("#lb-back .ic-back path"); const r = document.querySelector("#lb-back").getBoundingClientRect(), b = p.getBoundingClientRect(); return { sw: p.getAttribute("stroke-width"), off: Math.abs((b.left + b.right) / 2 - (r.left + r.right) / 2) }; });
  if (bb.sw !== "2.9" || bb.off > 1.5) throw new Error("back chevron " + JSON.stringify(bb));
  await page.fill("#lb-gp-name", "All scales");
  await page.keyboard.press("Enter");
  await page.waitForSelector(".lb-toast.show");
  await lb((m) => { if (m.logbook.goals({ q: "All scales" }).length !== 1) throw new Error("rename failed"); });
  await page.click("#lb-gp-type");
  await page.waitForFunction(() => document.querySelector("#lb-gp-type")?.textContent.includes("other"));
  await page.click(".lb-addnote");
  await page.waitForSelector(".lb-note-wrap.open #lb-notearea");
  await page.fill("#lb-notearea", "C# minor harmonic still lumpy");
  await page.keyboard.press("Control+Enter");
  await page.waitForSelector(".lb-noteitem");
  await page.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  // cancel path leaves no note
  await page.click(".lb-addnote");
  await page.waitForSelector(".lb-note-wrap.open");
  await page.click("#lb-note-cancel");
  await page.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  if ((await page.locator(".lb-noteitem").count()) !== 1) throw new Error("cancel saved a note");
  if ((await page.locator(".lb-seg").count()) !== 1) throw new Error("practice list");
  await shot("09-goal-page");
  await page.click("#lb-gp-practice");
  await page.waitForSelector(".lb-ceremony.engage.in");
  await gone();
  await page.waitForSelector(".lb-hero.running");
  if ((await text("#lb-hero-goal")) !== "All scales") throw new Error("practice this");
  await page.click("#lb-stop"); // under 10 s → not kept, no bow
  await page.waitForSelector(".lb-hero.idle");
  const t = await text(".lb-toast");
  if (!t.includes("not kept")) throw new Error("toast " + t);
});
await step("history: calendar, day report, month by goal", async () => {
  await page.click('.lb-strip [data-go="/history"]');
  await page.waitForSelector(".lb-history");
  await page.click(".lb-day.today");
  await page.waitForSelector(".lb-today-list .lb-trow");
  const n = await page.locator(".lb-today-list .lb-trow").count();
  if (n !== 2) throw new Error("day rows " + n);
  if ((await page.locator(".lb-bar").count()) !== 2) throw new Error("bars");
  const tot = await text(".lb-totals");
  if (!tot.includes("1h 32m")) throw new Error("totals " + tot);
  // WSHED-59: every practiced day carries exactly one band; today (92 min) is "good"; nothing is gold-for-volume
  const bands = await page.$$eval(".lb-day.on", (els) => els.map((e) => [...e.classList].filter((c) => c.startsWith("b-"))));
  if (!bands.length || bands.some((b) => b.length !== 1)) throw new Error("bands " + JSON.stringify(bands));
  const todayCls = await page.getAttribute(".lb-day.today", "class");
  if (!/\bb-good\b/.test(todayCls) || /\bgold\b/.test(todayCls)) throw new Error("today class " + todayCls);
  const info = await page.$eval("#lb-cal-info", (b) => { const r = b.getBoundingClientRect(), g = b.closest(".lb-cal-wrap").getBoundingClientRect(); return { rightGap: g.right - r.right, belowGrid: r.top >= g.bottom - r.height - 12 }; });
  if (info.rightGap > 8 || !info.belowGrid) throw new Error("info button placement " + JSON.stringify(info));
  await shot("10-history");
  await page.click("#lb-cal-info");
  await page.waitForSelector(".lb-legend-wrap.open .lb-legend li");
  const rows = await page.locator(".lb-legend li").count();
  if (rows !== 7) throw new Error("legend rows " + rows);
  const w = await page.evaluate(() => ({ vw: innerWidth, doc: document.documentElement.scrollWidth }));
  if (w.doc > w.vw) throw new Error("legend widened " + JSON.stringify(w));
  await shot("10b-history-legend");
  await page.keyboard.press("Escape");
  await page.waitForSelector(".lb-legend-wrap", { state: "detached" });
});
await step("add time (long-press play)", async () => {
  await page.click('.lb-strip [data-go=""]');
  await page.waitForSelector("#lb-play");
  const box = await page.locator("#lb-play").boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.waitForTimeout(650); await page.mouse.up();
  await page.waitForSelector(".lb-picker-wrap.open");
  if (!(await text(".lb-sheet-title")).includes("Add time")) throw new Error("mode");
  await page.click('.lb-pick-row:has-text("Sight reading")');
  await page.waitForSelector("#lb-addtime-go");
  await page.click('.lb-minute-chips [data-m="15"]');
  await page.click("#lb-addtime-go");
  await page.waitForFunction(() => document.querySelectorAll(".lb-trow").length === 3);
  const total = await text(".lb-hero-total");
  if (!total.includes("1h 47m")) throw new Error("total " + total);
});
await step("metronome: practice → picker; stamp while running", async () => {
  await page.goto(`${BASE}/#/metronome`);
  await page.waitForSelector("#log-tempo");
  if ((await text("#log-tempo-label")) !== "practice") throw new Error("idle label");
  await page.click("#log-tempo");
  await page.waitForSelector(".lb-picker-wrap.open");
  await page.click('.lb-pick-row:has-text("Pathétique")');
  await page.waitForSelector(".lb-ceremony.engage.in");
  await gone();
  await page.waitForFunction(() => document.querySelector("#log-tempo-label")?.textContent === "♩ stamp");
  await page.waitForSelector(".session-chip:not([hidden])");
  await page.click("#log-tempo");
  await page.waitForSelector(".lb-toast.show");
  const bpm = await lb((m) => m.logbook.running().segment.bpm);
  if (!bpm) throw new Error("no bpm stamped");
  await shot("11-metronome-stamp");
});
await step("sight singing addAuto both branches (via API)", async () => {
  const r1 = await lb((m) => m.logbook.addAuto({ source: "sightsinging", label: "Book 1 Lesson 1 · ★★ · 80%", startedAt: Date.now() - 3 * 60000 }).kind);
  if (r1 !== "note") throw new Error("running → " + r1);
  await lb((m) => { m.logbook.running().segment.startedAt -= 20 * 60000; m.logbook.stop(); });
  const r2 = await lb((m) => m.logbook.addAuto({ source: "sightsinging", label: "Book 1 Lesson 2 · ★★★ · 95%", startedAt: Date.now() - 4 * 60000 }).kind);
  if (r2 !== "segment") throw new Error("idle → " + r2);
  await page.goto(`${BASE}/?app=1#/logbook`);
  await page.waitForSelector(".lb-hero.idle");
  await page.waitForFunction(() => [...document.querySelectorAll(".lb-trow-name")].some((e) => e.textContent === "Sight singing"));
  if ((await page.locator(".lb-trow .lb-auto").count()) !== 1) throw new Error("auto tag");
  await shot("12-today-full");
});
await step("reload with a running segment restores hero + chip", async () => {
  await lb((m) => m.logbook.start(m.logbook.goals({ q: "Path" })[0].id));
  await page.reload();
  await page.waitForSelector(".lb-hero.running");
  await page.waitForSelector(".session-chip:not([hidden])");
  await lb((m) => m.logbook.stop());
});
await step("migration: v1 doc in localStorage → v2 on load", async () => {
  await page.evaluate((f) => localStorage.setItem("ws.logbook.data", f), fixture);
  await page.goto(`${BASE}/?app=1#/logbook/goals`);
  await page.waitForSelector(".lb-library");
  await page.reload();
  await page.waitForSelector(".lb-library");
  const doc = await lb((m) => ({ v: m.logbook.doc.schemaVersion, goals: m.logbook.goals({ status: "all" }).map((g) => g.name), run: m.logbook.running()?.goal.name, notes: m.logbook.notes("g-chopin").length }));
  if (doc.v !== 2 || !doc.goals.includes("Free practice") || doc.run !== "Free practice" || doc.notes !== 5) throw new Error(JSON.stringify(doc));
  await page.click('.lb-row-main:has-text("Chopin")');
  await page.waitForSelector(".lb-noteitem");
  await shot("13-migrated-goal");
  await page.goto(`${BASE}/?app=1#/logbook`);
  await page.waitForSelector(".lb-hero.running");
  await shot("14-migrated-today");
});
await step("touch tap: pointerdown→up→leave→click fires play (WSHED-42)", async () => {
  await lb((m) => m.logbook.stop());
  await page.goto(`${BASE}/?app=1#/logbook`);
  await page.waitForSelector("#lb-play");
  await page.evaluate(() => {
    const el = document.querySelector("#lb-play");
    for (const t of ["pointerdown", "pointerup", "pointerout", "pointerleave"]) el.dispatchEvent(new PointerEvent(t, { bubbles: true, pointerType: "touch", isPrimary: true, button: 0 }));
    el.dispatchEvent(new MouseEvent("click", { bubbles: true }));
  });
  await page.waitForSelector(".lb-picker-wrap.open", { timeout: 3000 });
  await page.keyboard.press("Escape");
  await page.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  await page.tap("#lb-play");
  await page.waitForSelector(".lb-picker-wrap.open", { timeout: 3000 });
  await page.keyboard.press("Escape");
  await page.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
});
await step("pinned nav: header + strip stay in view when scrolled", async () => {
  await page.goto(`${BASE}/?app=1#/logbook/goals`);
  await page.waitForSelector(".lb-library");
  const strip = await page.locator("#nav-slot .lb-strip").count();
  if (strip !== 1) throw new Error("strip not in nav slot");
  await page.evaluate(() => { document.querySelector("#tool-root").insertAdjacentHTML("beforeend", '<div id="tall" style="height:3000px"></div>'); window.scrollTo(0, 1500); });
  await page.waitForTimeout(250);
  const r = await page.evaluate(() => ({ nav: document.querySelector(".navbar").getBoundingClientRect().top, strip: document.querySelector(".lb-strip").getBoundingClientRect().bottom, y: window.scrollY }));
  if (r.y < 1000 || r.nav < -1 || r.nav > 1 || r.strip <= 0) throw new Error(JSON.stringify(r));
  await shot("18-pinned-nav");
  await page.evaluate(() => { document.querySelector("#tall")?.remove(); window.scrollTo(0, 0); });
  await page.click("#nav-slot [data-go='']");
  await page.waitForSelector(".lb-hero");
});
await step("tool menu: Logbook / rule / instruments / rule / training; labels aligned", async () => {
  await page.goto(`${BASE}/#/metronome`);
  await page.waitForSelector(".picker-btn");
  await page.click(".picker-btn");
  await page.waitForSelector(".picker-menu:not([hidden])");
  const r = await page.evaluate(() => {
    const kids = [...document.querySelector(".picker-menu").children].map((el) => el.classList.contains("picker-rule") ? "—" : el.lastChild.textContent.trim());
    const xs = [...document.querySelectorAll(".picker-item")].map((el) => Math.round(el.getBoundingClientRect().left + parseFloat(getComputedStyle(el).paddingLeft) + el.querySelector(".picker-glyph").getBoundingClientRect().width));
    const gw = [...document.querySelectorAll(".picker-glyph")].map((el) => Math.round(el.getBoundingClientRect().width));
    return { kids, xs, gw };
  });
  const want = ["Logbook", "—", "Metronome", "Pitch pipe", "Tuner", "—", "Sight singing"];
  if (JSON.stringify(r.kids.map((k) => k.toLowerCase())) !== JSON.stringify(want.map((k) => k.toLowerCase()))) throw new Error("order " + JSON.stringify(r.kids));
  if (new Set(r.xs).size !== 1 || new Set(r.gw).size !== 1) throw new Error("misaligned " + JSON.stringify(r));
  await shot("19-tool-menu");
  await page.keyboard.press("Escape");
  await page.evaluate(() => localStorage.removeItem("ws.shell.activeTool"));
  await page.goto(`${BASE}/`);
  await page.waitForFunction(() => location.hash === "#/metronome", null, { timeout: 5000 });
});
await step("no pull-to-refresh / side-swipe nav: overscroll-behavior none on root (both axes)", async () => {
  const r = await page.evaluate(() => [getComputedStyle(document.documentElement).overscrollBehaviorY, getComputedStyle(document.body).overscrollBehaviorY, getComputedStyle(document.documentElement).overscrollBehaviorX, getComputedStyle(document.body).overscrollBehaviorX]);
  if (r.some((v) => v !== "none")) throw new Error(JSON.stringify(r));
});
await step("brand: wordmark, title and manifest say Chopinly (WSHED-46)", async () => {
  const r = await page.evaluate(async () => {
    const m = await (await fetch("/manifest.webmanifest", { cache: "no-cache" })).json();
    return { wordmark: document.querySelector(".wordmark")?.textContent.trim(), title: document.title, name: m.name, short: m.short_name, stale: /woodshed/i.test(document.body.innerText) };
  });
  if (r.wordmark !== "Chopinly" || !r.title.startsWith("Chopinly") || r.short !== "Chopinly" || !r.name.startsWith("Chopinly")) throw new Error(JSON.stringify(r));
  if (r.stale) throw new Error("stale brand");
});
await step("desktop layout", async () => {
  const d = await browser.newContext({ viewport: { width: 1200, height: 800 } });
  const p2 = await d.newPage();
  p2.on("pageerror", (e) => errors.push(`desktop pageerror: ${e.message}`));
  await p2.goto(`${BASE}/?app=1#/logbook`);
  await p2.waitForSelector(".lb-hero");
  await p2.click("#lb-play");
  await p2.waitForSelector(".lb-picker-wrap.open");
  await p2.waitForTimeout(300);
  await p2.screenshot({ path: `${S}/15-desktop-picker.png` });
  await p2.keyboard.press("Escape");
  await p2.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  await d.close();
});
await step("reduced motion: flows still work, no sheet animation", async () => {
  const c = await browser.newContext({ viewport: { width: 420, height: 860 }, reducedMotion: "reduce" });
  const p3 = await c.newPage();
  p3.on("pageerror", (e) => errors.push(`rm pageerror: ${e.message}`));
  await p3.goto(`${BASE}/?app=1#/logbook`);
  await p3.waitForSelector("#lb-play");
  await p3.click("#lb-play");
  await p3.waitForSelector(".lb-picker-wrap.open");
  await p3.fill("#lb-pick-q", "Octaves");
  await p3.keyboard.press("Enter");
  await p3.waitForFunction(() => document.activeElement?.id === "lb-create-name");
  await p3.keyboard.press("Enter");
  await p3.waitForSelector(".lb-ceremony.engage.in");
  const rmRing = await p3.evaluate(() => getComputedStyle(document.querySelector(".lb-cer-ring")).display);
  if (rmRing !== "none") throw new Error("ring shown under reduced motion");
  await gone(p3);
  await p3.waitForSelector(".lb-hero.running");
  await p3.waitForFunction(() => !document.querySelector(".lb-sheet-wrap"));
  await p3.evaluate(async () => { const m = await import("/js/lib/logbook.js"); const sg = m.logbook.running().segment; sg.startedAt -= 12 * 60000; m.logbook.save(); });
  await p3.click("#lb-stop");
  await p3.waitForSelector(".lb-ceremony.bow.in");
  const rmBow = await p3.evaluate(() => ({ num: document.querySelector(".lb-cer-num").textContent.trim(), bloom: getComputedStyle(document.querySelector(".lb-cer-bloom")).display }));
  if (rmBow.num !== "12min" || rmBow.bloom !== "none") throw new Error("rm bow " + JSON.stringify(rmBow));
  await p3.screenshot({ path: `${S}/16b-reduced-motion-bow.png` });
  await gone(p3);
  await p3.waitForSelector(".lb-hero.idle");
  await p3.screenshot({ path: `${S}/16-reduced-motion.png` });
  await c.close();
});
await step("offline: service worker serves the app", async () => {
  const c = await browser.newContext({ viewport: { width: 420, height: 860 } });
  const p4 = await c.newPage();
  p4.on("pageerror", (e) => errors.push(`offline pageerror: ${e.message}`));
  await p4.goto(`${BASE}/?app=1#/logbook`);
  await p4.waitForSelector("#lb-play");
  await p4.waitForFunction(async () => { const r = await navigator.serviceWorker.getRegistration(); return !!r?.active; }, null, { timeout: 20000 });
  await p4.waitForFunction(async () => (await caches.keys()).includes("chopinly-v16"), null, { timeout: 20000 });
  await p4.waitForFunction(async () => { const c = await caches.open("chopinly-v16"); return !!(await c.match("/js/tools/logbook/picker.js")); }, null, { timeout: 20000 });
  await c.setOffline(true);
  await p4.goto(`${BASE}/?app=1#/logbook/goals`);
  await p4.waitForSelector(".lb-library", { timeout: 15000 });
  await p4.click("#lb-lib-add");
  await p4.waitForSelector(".lb-create-wrap.open");
  await p4.screenshot({ path: `${S}/17-offline.png` });
  await c.close();
});
await browser.close();
if (errors.length) { console.log("ERRORS:\n" + errors.join("\n")); process.exit(1); }
console.log("ALL GREEN");
