#!/usr/bin/env node
// Bake the Bravura glyph outlines the PDF export draws (docs/COMPOSE_DESIGN.md §10.1). Run once per
// glyph-table change:   node dev/bake-bravura.mjs
// Why outlines and not the font: pdf-lib embeds a whole OTF mislabelled as TrueType and MuPDF
// rejects fontkit's CFF subset of Bravura (spike 2026-09-14), so the paper draws each glyph as a
// path — one form XObject per glyph per document — and no music font ships at all. Every glyph
// js/lib/staff/glyphs.js names, plus the time-signature and tuplet digits, is baked; the outline
// is in font units (1000 / em, y up), origin at the glyph's musical anchor as SMuFL defines it.
// Bravura is OFL 1.1 (fonts/BRAVURA-LICENSE.txt); outlines rendered into a document are not a font.
import { loadUmd } from "./lib/umd.mjs";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
const ROOT = new URL("..", import.meta.url).pathname;
const fontkit = loadUmd(join(ROOT, "vendor/pdflib/fontkit.umd.min.js"));
const { G, timeDigit, tupletDigit } = await import(join(ROOT, "js/lib/staff/glyphs.js"));

const SRC = "https://raw.githubusercontent.com/steinbergmedia/bravura/master/redist/otf/Bravura.otf";
const bytes = new Uint8Array(await (await fetch(SRC)).arrayBuffer());
const font = fontkit.create(bytes);
const version = font.version ?? String(font.name?.records?.version?.en ?? "?");
const cps = new Set();
for (const s of Object.values(G)) for (const ch of s) cps.add(ch.codePointAt(0));
for (let n = 0; n <= 9; n++) { cps.add(timeDigit(n).codePointAt(0)); cps.add(tupletDigit(n).codePointAt(0)); }
const glyphs = {};
for (const cp of [...cps].sort((a, b) => a - b)) {
  const g = font.glyphForCodePoint(cp);
  if (!g || g.id === 0) throw new Error(`Bravura has no glyph for U+${cp.toString(16)}`);
  const d = g.path.toSVG().replace(/(\d+\.\d\d)\d+/g, "$1");
  const b = g.bbox;
  glyphs[cp.toString(16)] = { a: Math.round(g.advanceWidth), b: [b.minX, b.minY, b.maxX, b.maxY].map((v) => Math.round(v)), d };
}
const out = `// Generated by dev/bake-bravura.mjs — do not edit. Bravura ${version} (OFL 1.1, fonts/BRAVURA-LICENSE.txt).
// { upm, glyphs: { "<hex codepoint>": { a: advance, b: [minX, minY, maxX, maxY], d: SVG path } } } in font units, y up.
export const BRAVURA = ${JSON.stringify({ upm: font.unitsPerEm, version, glyphs }, null, 0).replace(/},"/g, '},\n"')};
`;
writeFileSync(join(ROOT, "js/lib/compose/export/bravura.js"), out);
console.log("baked", Object.keys(glyphs).length, "glyphs; Bravura", version, ";", out.length, "bytes");
